### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by dcousens** [dcousens/joinmarket#1]
Things to ask @chris-belcher

* What is the ping interval? A rudimentary keep-alive?
* `push`/`tx` are almost the exact same. Why?
* Message format, ` ~` is the end, ` ;` is a delimiter?  Is that an IRC thing?  Why not just split over lines like most IRC clients do

**Comment by dcousens** [comment]
Totally WIP module, but intending to be a drop in,  ideally no interaction with private keys,  just the protocol/events oriented.

**Comment by chris-belcher** [comment]
The ping interval is 180 seconds. Yes, a keep-alive. Otherwise the bot could take a very long time to detect that it's internet has gone down.

!tx is used in the coinjoin-creating procedure. It sends the unsigned transaction by the taker to every maker, who then check it and reply with signatures using !sig. However !push is not to do with coinjoin-creating, it can be used by the taker to ask the maker to broadcast a fully-signed transaction to the bitcoin network. This can be used to mess up IP-tracking. See this post https://www.reddit.com/r/joinmarket/comments/3450f2/winning_the_war_against_chainalysis_and_other_ip/

It's not an IRC thing. It's just used by our protocol to split up JoinMarket messages over many IRC messages. For example transactions data can be bigger than what fits into an IRC line.

You should be aware that I'm currently working on multi server IRC as in #116, it will be backwards compatible though, so old bots will still be able to talk to new bots but only on one server.

**Comment by dcousens** [comment]
Thanks @chris-belcher
